### ISSUE TITLE
in _convert_timestamp raise ValueError(timestamp) error

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [lux4rd0/weatherflow-collector#31]
I am trying to move to influx 2 using the new container (I have the old one working)...this is before I dump influx because of how randomly they keep changing query language directions and just standardizing on postgres time db.

I am getting this error. This is an existing working influx2 setup in a new bucket with a full access token.

Any ideas?

```
2024-12-06 18:15:47 - storage.influxdb - InfluxDBStorage - save_data - ERROR - Error writing to InfluxDB: 1733537730.0
Traceback:
Traceback (most recent call last):
  File "/app/weatherflow-collector/storage/influxdb.py", line 294, in save_data
    await self.write_api.write(
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write_api_async.py", line 117, in write
    self._serialize(record, write_precision, payloads, precision_from_point=False, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/_base.py", line 478, in _serialize
    self._serialize(record.to_line_protocol(precision=precision), precision, payload, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write/point.py", line 236, in to_line_protocol
    _time = _append_time(self._time, self._write_precision if precision is None else precision)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write/point.py", line 316, in _append_time
    return f" {int(_convert_timestamp(time, write_precision))}"
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write/point.py", line 360, in _convert_timestamp
    raise ValueError(timestamp)
ValueError: 1733537730.0
```

**Comment by disruptivepatternmaterial** [comment]
found the error

**Comment by disruptivepatternmaterial** [comment]
opps no I didnt :) there is something with the precision, if I remove that tag it works mostly...so not sure what is happening.

**Comment by lux4rd0** [comment]
@disruptivepatternmaterial—the issue is that WeatherFlow has made the "rapid_wind" socket API so that the timestamp is no longer an integer but a float. I didn't force a normalization before sending it to InfluxDB, so it complains.

```
{
   "device_id": 122367,
   "hub_sn": "HB-00130774",
   "ob": [
      1733343220.0,
      0.53,
      288
   ],
   "serial_number": "ST-00123555",
   "type": "rapid_wind"
}
```

It should be:

1733343220

It's also not on all of the messages (only some nodes at WeatherfFlow have the issue). WeatherFlow has stated that they've fixed it, but it isn't really. :)

I fixed my latest unreleased 6.0 version but have yet to port it back to previous versions. Which version are you on? I'll try to get it fixed without having to upgrade.

Thankfully, it's only for wind - but it still needs improvement.

**Comment by disruptivepatternmaterial** [comment]
So I am using 3:5:3 and latest...because I am dumping the data into influx 1.8 and 2 as I have been too lazy to completely switch and then when influx said they were dumping everything and moving to SQL I was like WTF and just stopped even bothering to convert....and hard drives are not too expensive anymore :)

**Comment by disruptivepatternmaterial** [comment]
Im guessing it is something in exec-remote-socket.sh...the wind_speed needs to be cast different in jq? I have no idea what I am talking about other than I have written code for like 40 years but never jq/shell script like those!

**Comment by lux4rd0** [comment]
I made a new version:

lux4rd0/weatherflow-collector:3.5.4

But that 3 branch is almost 3 years old :) LOL - I no longer have a way to test. But the fix should work. The underlying OS and docker images also needed to be updated, so let me know. :)

**Comment by n3bkv** [comment]
I think I'm having the same issue (seeing Rest-Down) but am pretty new to Docker so if you can update the OS and Docker images I can test for you.

**Comment by jameswilso** [comment]
Did the docker images get updated - I'm having the same issue but think the image is from the mid of last year. I've got the latest tag identified in docker.
